from __future__ import annotations

import math


def build_mock_ply() -> bytes:
    """Build a small colored point cloud in ASCII PLY format."""
    points: list[tuple[float, float, float, int, int, int]] = []
    steps = 240

    for index in range(steps):
        angle = (index / steps) * math.tau * 3
        radius = 0.35 + 0.25 * math.sin(angle * 1.7)
        x = radius * math.cos(angle)
        y = radius * math.sin(angle)
        z = -0.9 + (1.8 * index / (steps - 1))

        red = int(127 + 128 * math.sin(angle))
        green = int(127 + 128 * math.sin(angle + 2.1))
        blue = int(127 + 128 * math.sin(angle + 4.2))
        points.append((x, y, z, red, green, blue))

    header = [
        "ply",
        "format ascii 1.0",
        "comment mock reconstruction generated by FastAPI",
        f"element vertex {len(points)}",
        "property float x",
        "property float y",
        "property float z",
        "property uchar red",
        "property uchar green",
        "property uchar blue",
        "end_header",
    ]

    body = [
        f"{x:.6f} {y:.6f} {z:.6f} {red} {green} {blue}"
        for x, y, z, red, green, blue in points
    ]
    payload = "\n".join(header + body) + "\n"
    return payload.encode("utf-8")

